// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

//! The local Kusama <> Polkadot bridge pair: shared constants, the per-runtime typed operations
//! (generated by the shared macros in [`crate::common`]), bridge-relayer reward queries and the
//! network/bootstrap environment ([`environment`]). The individual tests live in `asset_transfer`.
//!
//! Unlike the Rococo <> Westend pair, the Polkadot/Kusama relay runtimes have **no `sudo` pallet**,
//! so the bridge is bootstrapped purely from genesis (HRMP channels, XCM version, bridge-GRANDPA
//! owner and funded sovereign/reward accounts) rather than via `sudo`-signed governance — see
//! [`environment`]. The two runtimes also identify each other by the named `NetworkId::Polkadot` /
//! `NetworkId::Kusama` variants (not `ByGenesis`), and DOT/KSM use 10/12 decimals respectively.

use subxt::{OnlineClient, PolkadotConfig};

// `1u64 << 60` — the amount the genesis override endows every well-known account with on the Bridge
// Hubs. The finality/parachain relayers (`//Charlie` / `//Dave`) only submit free or mandatory
// headers, so their balance must stay exactly at this value throughout the tests.
pub const ENDOWMENT: u128 = 1u128 << 60;

/// Message lane shared by both Asset Hubs (`0x00000001`).
pub const LANE_ID: [u8; 4] = [0, 0, 0, 1];
/// Target XCM version configured for every remote location.
pub const XCM_VERSION: u32 = 5;

// Bridged chain ids (`*b"bhpd"` / `*b"bhks"`), used as reward keys on the Bridge Hubs. `bhpd`
// (Bridge Hub Polkadot) keys rewards on Kusama BH; `bhks` (Bridge Hub Kusama) keys rewards on
// Polkadot BH.
pub const BRIDGED_CHAIN_ID_BHPD: [u8; 4] = *b"bhpd";
pub const BRIDGED_CHAIN_ID_BHKS: [u8; 4] = *b"bhks";

// Native-token decimals differ across the two ecosystems: DOT has 10, KSM has 12.
pub const POLKADOT_UNIT: u128 = 10_000_000_000;
pub const KUSAMA_UNIT: u128 = 1_000_000_000_000;

// Para ids (both Bridge Hubs use 1002, both Asset Hubs use 1000).
pub const ASSET_HUB_PARA_ID: u32 = 1000;
pub const BRIDGE_HUB_POLKADOT_PARA_ID: u32 = 1002;
pub const BRIDGE_HUB_KUSAMA_PARA_ID: u32 = 1002;

// Sovereign / reward accounts funded on the Bridge Hubs (SS58; the SS58 prefix is decorative — only
// the underlying 32 bytes are used). On Polkadot BH: the sibling Asset Hub sovereign account (pays
// XCM execution) and the lane reward accounts keyed by `bhks`.
const ASSET_HUB_SOVEREIGN_AT_BRIDGE_HUB_POLKADOT: &str =
	"13cKp89SgdtqUngo2WiEijPrQWdHFhzYZLf2TJePKRvExk7o";
const BHP_LANE_THIS_CHAIN: &str = "13E5fui93Uyua5RtDv2LQj4aVBBHo6YREe3n6CBwYdqNqoxj";
const BHP_LANE_BRIDGED_CHAIN: &str = "13E5fui93Uyua5RtDv2c9kcAbfrVFeeHyJzHe8sn1Ti77Afd";
// On Kusama BH: the sibling Asset Hub sovereign account and the lane reward accounts keyed by
// `bhpd`.
const ASSET_HUB_SOVEREIGN_AT_BRIDGE_HUB_KUSAMA: &str =
	"FBeL7EFTDeHnuViqaUHUXvhhUusN5FawDmHgfvzF97DXFr3";
const BHK_LANE_THIS_CHAIN: &str = "EoQBtnwp4jMtCEpV7C88rKrz6x1qMBh2z74ibGSqtZRnuMM";
const BHK_LANE_BRIDGED_CHAIN: &str = "EoQBtnwp4jMtCEpV7CPsssT6bdDHuHZmf3aGXxHJiSA4Dz3";

// The amount funded onto each sovereign/reward account (a single generous value works for both,
// since it only needs to cover XCM execution + reward payouts).
const SOVEREIGN_FUNDING: u128 = 250_000_000_000_000;

// The typed-operation macros are `#[macro_use]`d from `crate::common`. Polkadot/Kusama identify
// each other by the named `NetworkId` variants, and there is no relay-chain `sudo`, so `relay_ops!`
// is not used here (the relay-chain state is configured at genesis instead).
asset_hub_ops!(asset_hub_polkadot, asset_hub_polkadot, NetworkId::Kusama);
asset_hub_ops!(asset_hub_kusama, asset_hub_kusama, NetworkId::Polkadot);
bridge_hub_ops!(bridge_hub_polkadot, bridge_hub_polkadot, NetworkId::Kusama);
bridge_hub_ops!(bridge_hub_kusama, bridge_hub_kusama, NetworkId::Polkadot);

/// Reads `bridgeRelayers.relayerRewards(relayer, RewardsAccountParams)` on Bridge Hub Kusama (the
/// reward kind is a plain `RewardsAccountParams` there), keyed by the source Bridge Hub Polkadot
/// (`bhpd`).
pub async fn bridge_hub_kusama_relayer_reward(
	client: &OnlineClient<PolkadotConfig>,
	relayer: subxt::utils::AccountId32,
) -> Result<Option<u128>, anyhow::Error> {
	use crate::bridge_hub_kusama::runtime_types::{
		bp_messages::lane::LegacyLaneId,
		bp_relayers::{RewardsAccountOwner, RewardsAccountParams},
	};
	let reward = RewardsAccountParams {
		owner: RewardsAccountOwner::ThisChain,
		bridged_chain_id: BRIDGED_CHAIN_ID_BHPD,
		lane_id: LegacyLaneId(LANE_ID),
	};
	let addr = crate::bridge_hub_kusama::storage()
		.bridge_relayers()
		.relayer_rewards(relayer, reward);
	Ok(client.storage().at_latest().await?.fetch(&addr).await?)
}

/// Reads `bridgeRelayers.relayerRewards(relayer, BridgeReward::PolkadotKusamaBridge(..))` on Bridge
/// Hub Polkadot (the reward kind is wrapped in the runtime's `BridgeReward` enum there), keyed by
/// the source Bridge Hub Kusama (`bhks`).
pub async fn bridge_hub_polkadot_relayer_reward(
	client: &OnlineClient<PolkadotConfig>,
	relayer: subxt::utils::AccountId32,
) -> Result<Option<u128>, anyhow::Error> {
	use crate::bridge_hub_polkadot::runtime_types::{
		bp_messages::lane::LegacyLaneId,
		bp_relayers::{RewardsAccountOwner, RewardsAccountParams},
		bridge_hub_polkadot_runtime::bridge_common_config::BridgeReward,
	};
	let reward = BridgeReward::PolkadotKusamaBridge(RewardsAccountParams {
		owner: RewardsAccountOwner::ThisChain,
		bridged_chain_id: BRIDGED_CHAIN_ID_BHKS,
		lane_id: LegacyLaneId(LANE_ID),
	});
	let addr = crate::bridge_hub_polkadot::storage()
		.bridge_relayers()
		.relayer_rewards(relayer, reward);
	Ok(client.storage().at_latest().await?.fetch(&addr).await?)
}

/// Asserts that `//Charlie` and `//Dave` keep exactly the genesis endowment on both Bridge Hubs
/// (the finality/parachain relayers submit only free or mandatory headers, so their balance must
/// not change across a test).
pub async fn assert_relayer_balances_unchanged(
	bhp: &OnlineClient<PolkadotConfig>,
	bhk: &OnlineClient<PolkadotConfig>,
	charlie: [u8; 32],
	dave: [u8; 32],
) -> Result<(), anyhow::Error> {
	for (name, balance) in [
		("Charlie@PolkadotBH", bridge_hub_polkadot::free_balance(bhp, charlie).await?),
		("Dave@PolkadotBH", bridge_hub_polkadot::free_balance(bhp, dave).await?),
		("Charlie@KusamaBH", bridge_hub_kusama::free_balance(bhk, charlie).await?),
		("Dave@KusamaBH", bridge_hub_kusama::free_balance(bhk, dave).await?),
	] {
		anyhow::ensure!(
			balance == ENDOWMENT,
			"relayer {name} balance changed: {balance} != {ENDOWMENT}"
		);
	}
	Ok(())
}

mod environment;
pub use environment::BridgeTestEnv;

// Re-exported so the per-pair tests can reach the generic helpers via `crate::kusama_polkadot::*`.
pub use crate::common::utils::{dev_account, dev_public, retry_until};

mod asset_transfer;
