[package]
name = "finality-relay"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Finality proofs relay"
publish = false

[lints]
workspace = true

[dependencies]
async-std = "1.6.5"
async-trait = "0.1.79"
backoff = "0.4"
bp-header-chain = { path = "../../primitives/header-chain" }
futures = "0.3.30"
log = { workspace = true }
num-traits = "0.2"
relay-utils = { path = "../utils" }

[dev-dependencies]
parking_lot = "0.12.1"
