version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 20
  ignore:
  # Bridges polkadot-sdk dependencies
  - dependency-name: bp-*
    versions:
      - ">= 0"
  - dependency-name: bridge-runtime-common
    versions:
      - ">= 0"
  - dependency-name: equivocation-detector
    versions:
      - ">= 0"
  - dependency-name: finality-relay
    versions:
      - ">= 0"
  - dependency-name: messages-relay
    versions:
      - ">= 0"
  - dependency-name: parachains-relay
    versions:
      - ">= 0"
  - dependency-name: relay-substrate-client
    versions:
      - ">= 0"
  - dependency-name: relay-utils
    versions:
      - ">= 0"
  - dependency-name: substrate-relay-helper
    versions:
      - ">= 0"
  # Substrate polkadot-sdk (+ Polkadot/Cumulus pallets) dependencies
  - dependency-name: beefy-*
    versions:
    - ">= 0"
  - dependency-name: frame-*
    versions:
    - ">= 0"
  - dependency-name: fork-tree
    versions:
    - ">= 0"
  - dependency-name: mmr-*
    versions:
    - ">= 0"
  - dependency-name: node-inspect
    versions:
    - ">= 0"
  - dependency-name: pallet-*
    versions:
    - ">= 0"
  - dependency-name: sc-*
    versions:
    - ">= 0"
  - dependency-name: sp-*
    versions:
    - ">= 0"
  - dependency-name: substrate-*
    versions:
    - ">= 0"
  - dependency-name: try-runtime-cli
    versions:
    - ">= 0"
  - dependency-name: binary-merkle-tree
    versions:
    - ">= 0"
  # Polkadot polkadot-sdk dependencies
  - dependency-name: kusama-*
    versions:
    - ">= 0"
  - dependency-name: polkadot-*
    versions:
    - ">= 0"
  - dependency-name: xcm*
    versions:
    - ">= 0"
  # Cumulus polkadot-sdk dependencies
  - dependency-name: cumulus-*
    versions:
    - ">= 0"
  - dependency-name: parachain-info
    versions:
    - ">= 0"
  rebase-strategy: disabled
