[package]
name = "ethereum-contract-builtin"
description = "Small crate that helps Solidity contract to verify finality proof."
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]

# General dependencies

codec = { package = "parity-scale-codec", version = "1.0.0" }
sc-finality-grandpa = "0.8.0-alpha.5"

# Runtime/chain specific dependencies

bridge-node-runtime = { path = "../../../bin/node/runtime" }
