{
 "title": "BridgeHubKusama <> BridgeHubPolkadot maintenance (00000001)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Relay build commit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_relay_build_info{domain=\"parity-chains\"}",
     "legendFormat": "{{commit}}"
    }
   ]
  },
  {
   "title": "Relay build version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_relay_build_info{domain=\"parity-chains\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Is relay running?",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{domain=\"parity-chains\",container=\"bridges-common-relay\"}",
     "legendFormat": "Is relay running"
    }
   ]
  },
  {
   "title": "Is relay running? (for alert)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "up{domain=\"parity-chains\",container=\"bridges-common-relay\"}",
     "legendFormat": "Is relay running"
    }
   ]
  },
  {
   "title": "Relay errors/warnings per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "count_over_time({container=\"bridges-common-relay\"} |~ `(?i)(warn|error|fail)` [1m])",
     "legendFormat": "Errors per minute"
    }
   ]
  },
  {
   "title": "Kusama headers mismatch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "Kusama_to_BridgeHubPolkadot_Sync_is_source_and_source_at_target_using_different_forks{domain=\"parity-chains\"}",
     "legendFormat": "Best BridgeHubKusama header at BridgeHubPolkadot doesn't match the same header of BridgeHubKusama"
    }
   ]
  },
  {
   "title": "Polkadot headers mismatch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 14 },
   "targets": [
    {
     "expr": "Polkadot_to_BridgeHubKusama_Sync_is_source_and_source_at_target_using_different_forks{domain=\"parity-chains\"}",
     "legendFormat": "Best BridgeHubKusama header at BridgeHubPolkadot doesn't match the same header of BridgeHubKusama"
    }
   ]
  },
  {
   "title": "BridgeHubKusama headers mismatch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "BridgeHubKusama_to_BridgeHubPolkadot_MessageLane_00000001_is_source_and_source_at_target_using_different_forks{domain=\"parity-chains\"}",
     "legendFormat": "Best BridgeHubKusama header at BridgeHubPolkadot doesn't match the same header of BridgeHubKusama"
    }
   ]
  },
  {
   "title": "BridgeHubPolkadot headers mismatch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 21 },
   "targets": [
    {
     "expr": "BridgeHubPolkadot_to_BridgeHubKusama_MessageLane_00000001_is_source_and_source_at_target_using_different_forks{domain=\"parity-chains\"}",
     "legendFormat": "Best BridgeHubKusama header at BridgeHubPolkadot doesn't match the same header of BridgeHubKusama"
    }
   ]
  },
  {
   "title": "Relay balances at KusamaBridgeHub",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "at_BridgeHubKusama_relay_BridgeHubPolkadotMessages_balance{domain=\"parity-chains\"}",
     "legendFormat": "Messages Relay Balance"
    }
   ]
  },
  {
   "title": "Relay balances at PolkadotBridgeHub",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 28 },
   "targets": [
    {
     "expr": "at_BridgeHubPolkadot_relay_BridgeHubKusamaMessages_balance{domain=\"parity-chains\"}",
     "legendFormat": "Messages Relay Balance"
    }
   ]
  }
 ]
}