[package]
name = "relay-westend-client"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true

[lints]
workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", features = ["derive"] }
scale-info = { version = "2.11.3", default-features = false, features = ["derive"] }
subxt = { version = "0.35.3", default-features = false, features = ["native"] }

# Bridge dependencies

bp-polkadot-core = { git = "https://github.com/paritytech/polkadot-sdk", branch = "sv-fix-relayer-version-metric" }
bp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", branch = "sv-fix-relayer-version-metric" }
bp-westend = { git = "https://github.com/paritytech/polkadot-sdk", branch = "sv-fix-relayer-version-metric" }

relay-substrate-client = { git = "https://github.com/paritytech/polkadot-sdk", branch = "sv-fix-relayer-version-metric" }
relay-utils = { git = "https://github.com/paritytech/polkadot-sdk", branch = "sv-fix-relayer-version-metric" }

# Substrate Dependencies

sp-consensus-grandpa = { git = "https://github.com/paritytech/polkadot-sdk", branch = "sv-fix-relayer-version-metric" }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", branch = "sv-fix-relayer-version-metric" }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", branch = "sv-fix-relayer-version-metric" }
sp-session = { git = "https://github.com/paritytech/polkadot-sdk", branch = "sv-fix-relayer-version-metric" }
sp-weights = { git = "https://github.com/paritytech/polkadot-sdk", branch = "sv-fix-relayer-version-metric" }
