// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

//! Zombienet-sdk based integration tests for the local Rococo <> Westend bridge.
//!
//! They spawn two relay-chain networks (Rococo and Westend), each with a Bridge Hub and an Asset
//! Hub parachain, drive the external `substrate-relay` binary as a set of subprocesses and assert
//! on-chain state via `subxt`. Everything is gated behind the `zombie-ci` feature.
//!
//! `codegen/*.rs` are the typed `subxt` clients for the six runtimes, generated by
//! `tools/runtime-codegen --full` (see `testing/metadata-gen`). Each is a `pub mod api { .. }`,
//! re-exported below under the chain name so call sites use `crate::<chain>::{tx, storage,
//! runtime_types, ..}`.

macro_rules! runtime_codegen {
	($module:ident, $file:literal) => {
		#[cfg(feature = "zombie-ci")]
		#[path = $file]
		mod $module;
	};
}

runtime_codegen!(rococo_codegen, "codegen/rococo.rs");
runtime_codegen!(westend_codegen, "codegen/westend.rs");
runtime_codegen!(asset_hub_rococo_codegen, "codegen/asset_hub_rococo.rs");
runtime_codegen!(asset_hub_westend_codegen, "codegen/asset_hub_westend.rs");
runtime_codegen!(bridge_hub_rococo_codegen, "codegen/bridge_hub_rococo.rs");
runtime_codegen!(bridge_hub_westend_codegen, "codegen/bridge_hub_westend.rs");

#[cfg(feature = "zombie-ci")]
pub use {
	asset_hub_rococo_codegen::api as asset_hub_rococo,
	asset_hub_westend_codegen::api as asset_hub_westend,
	bridge_hub_rococo_codegen::api as bridge_hub_rococo,
	bridge_hub_westend_codegen::api as bridge_hub_westend, rococo_codegen::api as rococo,
	westend_codegen::api as westend,
};

// Reusable, bridge-pair-agnostic test infrastructure.
#[cfg(feature = "zombie-ci")]
mod common;

// The Rococo <> Westend bridge pair (constants, typed ops, environment and its tests).
#[cfg(feature = "zombie-ci")]
mod rococo_westend;
