// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

//! Zombienet-sdk based integration tests for the local Rococo <> Westend bridge.
//!
//! They spawn two relay-chain networks (Rococo and Westend), each with a Bridge Hub and an Asset
//! Hub parachain, drive the external `substrate-relay` binary as a set of subprocesses and assert
//! on-chain state via `subxt`. Everything is gated behind the `zombie-ci` feature.
//!
//! `codegen/*.rs` are the typed `subxt` clients for the six runtimes, generated by
//! `tools/runtime-codegen --full` (see `scripts/generate-codegen.sh`). Each is re-exported below
//! under its chain name, so call sites use `crate::<chain>::{tx, storage, runtime_types, ..}`.

macro_rules! runtime_codegen {
	($module:ident, $file:literal) => {
		#[cfg(feature = "zombie-ci")]
		#[path = $file]
		mod $module;
	};
}

runtime_codegen!(rococo_codegen, "codegen/rococo.rs");
runtime_codegen!(westend_codegen, "codegen/westend.rs");
runtime_codegen!(asset_hub_rococo_codegen, "codegen/asset_hub_rococo.rs");
runtime_codegen!(asset_hub_westend_codegen, "codegen/asset_hub_westend.rs");
runtime_codegen!(bridge_hub_rococo_codegen, "codegen/bridge_hub_rococo.rs");
runtime_codegen!(bridge_hub_westend_codegen, "codegen/bridge_hub_westend.rs");

runtime_codegen!(polkadot_codegen, "codegen/polkadot.rs");
runtime_codegen!(kusama_codegen, "codegen/kusama.rs");
runtime_codegen!(asset_hub_polkadot_codegen, "codegen/asset_hub_polkadot.rs");
runtime_codegen!(asset_hub_kusama_codegen, "codegen/asset_hub_kusama.rs");
runtime_codegen!(bridge_hub_polkadot_codegen, "codegen/bridge_hub_polkadot.rs");
runtime_codegen!(bridge_hub_kusama_codegen, "codegen/bridge_hub_kusama.rs");

#[cfg(feature = "zombie-ci")]
pub use {
	asset_hub_rococo_codegen::api as asset_hub_rococo,
	asset_hub_westend_codegen::api as asset_hub_westend,
	bridge_hub_rococo_codegen::api as bridge_hub_rococo,
	bridge_hub_westend_codegen::api as bridge_hub_westend, rococo_codegen::api as rococo,
	westend_codegen::api as westend,
};

#[cfg(feature = "zombie-ci")]
pub use {
	asset_hub_kusama_codegen::api as asset_hub_kusama,
	asset_hub_polkadot_codegen::api as asset_hub_polkadot,
	bridge_hub_kusama_codegen::api as bridge_hub_kusama,
	bridge_hub_polkadot_codegen::api as bridge_hub_polkadot, kusama_codegen::api as kusama,
	polkadot_codegen::api as polkadot,
};

// Reusable, bridge-pair-agnostic test infrastructure. `#[macro_use]` so the per-runtime
// typed-operation macros it defines are in scope for the bridge-pair modules below.
#[cfg(feature = "zombie-ci")]
#[macro_use]
mod common;

// The Rococo <> Westend bridge pair (constants, typed ops, environment and its tests).
#[cfg(feature = "zombie-ci")]
mod rococo_westend;

// The Kusama <> Polkadot bridge pair.
#[cfg(feature = "zombie-ci")]
mod kusama_polkadot;
