[package]
name = "runtime-codegen"
version = "0.1.0"
description = "Tool for generating bridge runtime code from metadata"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository = "https://github.com/paritytech/parity-bridges-common.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
clap = { version = "4.5.3", features = ["derive", "cargo"] }
codec = { package = "parity-scale-codec", version = "3.6.1", features = ["derive"] }
color-eyre = "0.6.1"
indoc = "2.0.5"
prettyplease = "0.2.20"
proc-macro2 = "1.0.56"
subxt-codegen = { version = "0.38.0" }
subxt-utils-fetchmetadata = { version = "0.38.0", features = ["url"] }
wasm-loader = { git = "https://github.com/chevdor/subwasm", branch = "master" }
wasm-testbed = { git = "https://github.com/chevdor/subwasm", branch = "master" }
