[package]
name = "runtime-codegen"
version = "0.1.0"
description = "Tool for generating bridge runtime code from metadata"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository = "https://github.com/paritytech/parity-bridges-common.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
clap = { workspace = true }
codec = { workspace = true }
color-eyre = { workspace = true }
indoc = { workspace = true }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
subxt-codegen = { workspace = true }
subxt-utils-fetchmetadata = { workspace = true }
wasm-loader = { workspace = true }
wasm-testbed = { workspace = true }
