[package]
name = "bridge-node"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/parity-bridges-common/"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[[bin]]
name = "bridge-node"

[dependencies]
futures = "0.3.5"
jsonrpc-core = "14.2.0"
log = "0.4.8"
structopt = "0.3.15"
bridge-node-runtime = { version = "0.1.0", path = "../runtime" }
sp-bridge-eth-poa = { version = "0.1.0", path = "../../../primitives/ethereum-poa" }

[dependencies.sc-cli]
version = "0.8.0-rc4"

[dependencies.sc-rpc]
version = "2.0.0-rc4"

[dependencies.sp-core]
version = "2.0.0-rc4"

[dependencies.sc-executor]
version = "0.8.0-rc4"

[dependencies.sc-service]
version = "0.8.0-rc4"

[dependencies.sp-inherents]
version = "2.0.0-rc4"

[dependencies.sc-transaction-pool]
version = "2.0.0-rc4"

[dependencies.sp-transaction-pool]
version = "2.0.0-rc4"

[dependencies.sc-network]
version = "0.8.0-rc4"

[dependencies.sc-consensus-aura]
version = "0.8.0-rc4"

[dependencies.sp-consensus-aura]
version = "0.8.0-rc4"

[dependencies.sp-consensus]
version = "0.8.0-rc4"

[dependencies.grandpa]
package = "sc-finality-grandpa"
version = "0.8.0-rc4"

[dependencies.grandpa-primitives]
package = "sp-finality-grandpa"
version = "2.0.0-rc4"

[dependencies.sc-consensus]
version = "0.8.0-rc4"

[dependencies.sc-client-api]
version = "2.0.0-rc4"

[dependencies.sp-runtime]
version = "2.0.0-rc4"

[dependencies.sc-basic-authorship]
version = "0.8.0-rc4"

[dependencies.substrate-frame-rpc-system]
version = "2.0.0-rc4"

[dependencies.frame-benchmarking]
version = "2.0.0-rc4"

[dependencies.frame-benchmarking-cli]
version = "2.0.0-rc4"

[build-dependencies]
vergen = "3.1.0"

[build-dependencies.build-script-utils]
package = "substrate-build-script-utils"
version = "2.0.0-rc4"

[build-dependencies.frame-benchmarking-cli]
version = "2.0.0-rc4"

[features]
default = []
runtime-benchmarks = [
	"bridge-node-runtime/runtime-benchmarks",
]
