[package]
name = "substrate-bridge"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
async-std = "=1.5.0"
clap = "2.33.1"
ctrlc = "3.1.4"
derive_more = "0.99.9"
env_logger = "0.7.1"
futures = "0.3.5"
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee", features = ["ws"] }
log = "0.4.8"
serde_json = "1.0.56"
url = "2.1.0"

[dependencies.sp-core]
version = "2.0.0-rc4"
rev = "00768a1f21a579c478fe5d4f51e1fa71f7db9fd4"
git = "https://github.com/paritytech/substrate/"

[dependencies.sp-rpc]
version = "2.0.0-rc4"
rev = "00768a1f21a579c478fe5d4f51e1fa71f7db9fd4"
git = "https://github.com/paritytech/substrate/"

[dependencies.node-primitives]
version = "2.0.0-rc4"
rev = "00768a1f21a579c478fe5d4f51e1fa71f7db9fd4"
git = "https://github.com/paritytech/substrate/"
