version: '3.5'
services:
  relay-millau-headers-to-rialto:
    image: paritytech/substrate-relay
    entrypoint: /config/relay-millau-headers-to-rialto-entrypoint.sh
    volumes:
      - ./scripts:/config
    environment:
      RUST_LOG: rpc=trace,bridge=trace
    ports:
      - "9616:9616"
    depends_on: &all-nodes
      - millau-node-alice
      - millau-node-bob
      - millau-node-charlie
      - millau-node-dave
      - millau-node-eve

  prometheus-metrics:
    volumes:
      - ./dashboard/prometheus/:/etc/prometheus/
    depends_on: *all-nodes
