version: '3.5'
services:
  # We provide overrides for these particular nodes since they are public facing
  # nodes which we use to connect from things like Polkadot JS Apps.
  rialto-node-charlie:
    environment:
      VIRTUAL_HOST: wss.rialto.brucke.link
      VIRTUAL_PORT: 9944
      LETSENCRYPT_HOST: wss.rialto.brucke.link
      LETSENCRYPT_EMAIL: admin@parity.io

  millau-node-charlie:
    environment:
      VIRTUAL_HOST: wss.millau.brucke.link
      VIRTUAL_PORT: 9944
      LETSENCRYPT_HOST: wss.millau.brucke.link
      LETSENCRYPT_EMAIL: admin@parity.io

  relay-headers-millau-to-rialto:
    image: paritytech/substrate-relay
    entrypoint: /entrypoints/relay-headers-millau-to-rialto-entrypoint.sh
    volumes:
      - ./bridges/rialto-millau/entrypoints:/entrypoints
    environment:
      RUST_LOG: rpc=trace,bridge=trace
    ports:
      - "9616:9616"
    depends_on: &all-nodes
      - millau-node-alice
      - millau-node-bob
      - millau-node-charlie
      - millau-node-dave
      - millau-node-eve
      - rialto-node-alice
      - rialto-node-bob
      - rialto-node-charlie
      - rialto-node-dave
      - rialto-node-eve


  prometheus-metrics:
    volumes:
      - ./bridges/rialto-millau/dashboard/prometheus/:/etc/prometheus/
    depends_on: *all-nodes
