name:                   Check style

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - 'README.md'
      - diagrams
  schedule:             # Weekly build
    - cron:             '0 0 * * 0'
jobs:
## Check stage
  check-fmt:
    name:                          Check RustFmt
    runs-on:                       ubuntu-latest
    env:
      RUST_BACKTRACE:   full
    steps:
      - name:           Cancel Previous Runs
        uses:           styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - name:           Checkout sources & submodules
        uses:           actions/checkout@master
        with:
          fetch-depth:  5
          submodules:   recursive
      - name:           Add rustfmt
        run:            rustup component add rustfmt
      - name:           rust-fmt check
        uses:           actions-rs/cargo@master
        with:
          command:      fmt
          args:         --all -- --check
  check-clippy:
    name:                          Check Clippy
    runs-on:                       self-hosted
    container:
      image:                       paritytech/ci-linux:production
      volumes:
        - /cache:/cache
      options:                     --cpus 8
    env:
      RUST_BACKTRACE:              full
      SCCACHE_REDIS:               redis://172.17.0.1/0
      SCCACHE_IDLE_TIMEOUT:        0
      CMAKE_C_COMPILER_LAUNCHER:   sccache
      CMAKE_CXX_COMPILER_LAUNCHER: sccache
    steps:
      - name:                      Checkout sources & submodules
        uses:                      actions/checkout@master
        with:
          fetch-depth:             5
          submodules:              recursive
      - name:                      Configure CARGO_HOME & CARGO_TARGET_DIR
        run:                       ./scripts/ci-cache.sh "${{ github.head_ref }}" "nightly-clippy"
      - name:                      Add clippy
        run:                       rustup component add clippy --toolchain nightly
      - name:                      Fetch
        uses:                      actions-rs/cargo@master
        with:
          command:                 fetch
          toolchain:               nightly
      - name:                      Clippy
        uses:                      actions-rs/cargo@master
        with:
          command:                 clippy
          toolchain:               nightly
          args:                    --all-targets -- -D warnings
      - name:                      Stats sccache
        if:                        always()
        run:                       sccache --show-stats
