name:                              Check, test and build Suite

on:
# Uncomment when needed
#  pull_request:
#  push:
#    branches:
#      - master
#    tags:
#      - v*
#    paths-ignore:
#      - 'README.md'
#      - diagrams/
  schedule:                        #Nightly build
    - cron:                        '0 0 * * *'
jobs:

## Check stage
  check-style:
    name:                          Check format and clippy
    runs-on:                       self-hosted
    container:                     paritytech/ci-linux:production
    env:
      RUST_BACKTRACE:              full
    steps:
      - name:                      Checkout sources & submodules
        uses:                      actions/checkout@master
        with:
          fetch-depth:             5
          submodules:              recursive
      - name:                      Add rustfmt and clippy
        run:                       rustup component add rustfmt clippy --toolchain nightly
      - name:                      Style check
        uses:                      actions-rs/cargo@master
        with:
          command:                 fmt
          toolchain:               nightly
          args:                    --all -- --check
      - name:                      Fetch
        uses:                      actions-rs/cargo@master
        with:
          command:                 fetch
          toolchain:               nightly
      - name:                      Clippy
        uses:                      actions-rs/cargo@master
        with:
          command:                 clippy
          toolchain:               nightly
          args:                    --all-targets -- -D warnings
