name:                              Check style

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - 'README.md'
      - diagrams
  schedule:                        # Weekly build
    - cron:                        '0 0 * * 0'
jobs:
## Check stage
  check-fmt:
    name:                          Check RustFmt
    runs-on:                       self-hosted
    container:                     paritytech/ci-linux:production
    env:
      RUST_BACKTRACE:              full
    steps:
      - name:                      Checkout sources & submodules
        uses:                      actions/checkout@master
        with:
          fetch-depth:             5
          submodules:              recursive
      - name:                      Add rustfmt
        run:                       rustup component add rustfmt --toolchain nightly
      - name:                      rust-fmt check
        uses:                      actions-rs/cargo@master
        with:
          command:                 fmt
          toolchain:               nightly
          args:                    --all -- --check
