name:                  Check style

on:
  pull_request:
  push:
    branches:
      - master
      - stable
    tags:
      - v*
    paths-ignore:
      - 'README.md'
      - diagrams/
jobs:
## Check stage
  test:
    name:              Check
    runs-on:           ubuntu-latest
    container: paritytech/ci-linux:production
    env:
      RUST_BACKTRACE:  full
    steps:
      - name:          Checkout sources & submodules
        uses:          actions/checkout@master
        with:
          fetch-depth: 5
          submodules:  recursive
      - name: Configure cargo data directory
        run: echo "::set-env name=CARGO_HOME::$(pwd)/target/cargo"
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |-
            target/cargo
            target/sccache
            target/*/.*
            target/*/build
            target/*/deps
          key: clippy-${{ hashFiles('Cargo.lock') }}
          restore-keys: clippy-
      - name: Start sccache
        env:
          SCCACHE_DIR: ${{ github.workspace }}/target/sccache
          SCCACHE_CACHE_SIZE: 1G
          SCCACHE_IDLE_TIMEOUT: 0
        run: sccache --start-server
      - name:          Set sccache ENV
        run:  |
          echo "::set-env name=CMAKE_C_COMPILER_LAUNCHER::sccache"
          echo "::set-env name=CMAKE_CXX_COMPILER_LAUNCHER::sccache"
      - name:          Style check
        uses:          actions-rs/cargo@master
        with:
          command:     fmt
          args:        --all -- --check
      - name:          Fetch
        uses:          actions-rs/cargo@master
        with:
          command:     fetch
      - name:          Clippy
        uses:          actions-rs/cargo@master
        with:
          command:     clippy
          args:        --all-targets -- -D warnings
