{
 "title": "Ethereum to Substrate headers sync dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Block difference",
   "type": "graph",
   "description": "Difference between source & target blocks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(Ethereum_to_Substrate_Sync_best_block_numbers{node=\"source\"}) - max(Ethereum_to_Substrate_Sync_best_block_numbers{node=\"target\"})"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Ethereum_to_Substrate_Sync_system_average_load",
     "legendFormat": "Average system load in last {{over}}"
    }
   ]
  },
  {
   "title": "Relay process CPU usage (1 CPU = 100)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Ethereum_to_Substrate_Sync_process_cpu_usage_percentage"
    }
   ]
  },
  {
   "title": "Best blocks relay knows of",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Ethereum_to_Substrate_Sync_best_block_numbers",
     "legendFormat": "Best known block on {{node}} node"
    }
   ]
  },
  {
   "title": "Memory used by relay process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Ethereum_to_Substrate_Sync_process_memory_usage_bytes / 1024 / 1024",
     "legendFormat": "Process memory, MB"
    }
   ]
  },
  {
   "title": "Blocks in state on relay",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Ethereum_to_Substrate_Sync_blocks_in_state",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Source blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(Ethereum_to_Substrate_Sync_best_block_numbers{node=\"source\"})"
    }
   ]
  }
 ]
}